---
title: "Hands-on Exercise 00: working with tidyverse"
author: "Moo Jia Rong"
date: "January 11, 2025"
date-modified: "last-modified"
execute:
  echo: true
  eval: true
  warning: false
  freeze: true 
---

### Getting started

#### Loading tidyverse onto r environment by using the code chunk below.

```{r}
pacman::p_load(tidyverse)
```

#### Importing data

```{r}
realis2019 <- read_csv('data/REALIS2019.csv')
```

```{r}
#| eval:FALSE
popdata_fat <- read_csv('data/PopData2019_fat.csv')
```

#### Pivoting data

```{r}
popdata_long <- popdata_fat %>% 
  pivot_longer(c(3:21),
               names_to = "Age Group",
               values_to = "Population")
```

#### Saving the data

```{r}
write_rds(popdata_long, 'rds/popdata_long.rds')
```

### Retrieving the rds files

```{r}
#| echo: FALSE
popdata_long<-read_rds('rds/popdata_long.rds')
```

#### working with dplyr

```{r}
realis2019_selected <- realis2019 %>%
  select('Project Name',
         'Transacted Price ($)',
         'Type of Sale',
         'Unit Price ($ psm)',
         'Property Type')
realis2019_selected
```

#### working with filter() of dplyr.

```{r}
realis2019_filtered <- realis2019_selected %>%
  filter(`Property Type` == 'Condominium'|
           `Property Type` == 'Apartment') %>%
  filter(`Type of Sale` == 'New Sale') %>%
  filter(`Unit Price ($ psm)` <= 13000)
```
