<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Moo Jia Rong">
<meta name="dcterms.date" content="2025-02-01">

<title>Take-home Exercise 1 – ISSS608</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-064ec00394a99716e5cda9b8933d5fee.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Take-home Exercise 1 – ISSS608">
<meta property="og:description" content="">
<meta property="og:image" content="https://www.jiarong-visual-analytics.netlify.app/Take-home_Exercise/Take-home_Ex01/Take-home_Ex01_files/figure-html/unnamed-chunk-8-1.png">
<meta property="og:site_name" content="ISSS608">
<meta property="og:image:height" content="960">
<meta property="og:image:width" content="1344">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS608</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex03a.html">
 <span class="dropdown-text">Hands-on Exercise 3a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex03b.html">
 <span class="dropdown-text">Hands-on Exercise 3b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex04a.html">
 <span class="dropdown-text">Hands-on Exercise 4a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex04b.html">
 <span class="dropdown-text">Hands-on Exercise 4b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex04c.html">
 <span class="dropdown-text">Hands-on Exercise 4c</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex04d.html">
 <span class="dropdown-text">Hands-on Exercise 4d</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex05a.html">
 <span class="dropdown-text">Hands-on Exercise 5a</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex05b.html">
 <span class="dropdown-text">Hands-on Exercise 5b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex05c.html">
 <span class="dropdown-text">Hands-on Exercise 5c</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex05d.html">
 <span class="dropdown-text">Hands-on Exercise 5d</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands_on_Exercise/Hands-on_Ex05e.html">
 <span class="dropdown-text">Hands-on Exercise 5e</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-Class_Exercise/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Exercise/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> <i class="bi bi-house-fill" role="img">
</i> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> <i class="bi bi-person-workspace" role="img">
</i> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of Contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><strong>1 Overview</strong></a>
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background"><strong>1.1 Background</strong></a></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset"><strong>1.2 Dataset</strong></a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives"><strong>1.3 Objectives</strong></a></li>
  </ul></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started"><strong>2 Getting Started</strong></a>
  <ul>
  <li><a href="#loading-packages" id="toc-loading-packages" class="nav-link" data-scroll-target="#loading-packages"><strong>2.1 Loading Packages</strong></a></li>
  <li><a href="#importing-data" id="toc-importing-data" class="nav-link" data-scroll-target="#importing-data"><strong>2.2 Importing Data</strong></a></li>
  </ul></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling"><strong>3 Data Wrangling</strong></a>
  <ul>
  <li><a href="#removing-irrelevant-data" id="toc-removing-irrelevant-data" class="nav-link" data-scroll-target="#removing-irrelevant-data"><strong>3.1 Removing irrelevant data</strong></a></li>
  <li><a href="#check-for-duplicated-or-missing-values" id="toc-check-for-duplicated-or-missing-values" class="nav-link" data-scroll-target="#check-for-duplicated-or-missing-values"><strong>3.2 Check for duplicated or missing values</strong></a></li>
  <li><a href="#recode-age" id="toc-recode-age" class="nav-link" data-scroll-target="#recode-age"><strong>3.3 Recode Age</strong></a></li>
  <li><a href="#recode-bmi" id="toc-recode-bmi" class="nav-link" data-scroll-target="#recode-bmi"><strong>3.4 Recode BMI</strong></a></li>
  <li><a href="#creating-blood-pressure-variable" id="toc-creating-blood-pressure-variable" class="nav-link" data-scroll-target="#creating-blood-pressure-variable"><strong>3.5 Creating blood pressure variable</strong></a></li>
  <li><a href="#recode-cholesterol-level" id="toc-recode-cholesterol-level" class="nav-link" data-scroll-target="#recode-cholesterol-level"><strong>3.6 Recode Cholesterol Level</strong></a></li>
  <li><a href="#ordering-levels-for-ordinal-categorical-variables" id="toc-ordering-levels-for-ordinal-categorical-variables" class="nav-link" data-scroll-target="#ordering-levels-for-ordinal-categorical-variables"><strong>3.7 Ordering levels for ordinal categorical variables</strong></a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis-and-statistical-visualisations" id="toc-exploratory-data-analysis-and-statistical-visualisations" class="nav-link" data-scroll-target="#exploratory-data-analysis-and-statistical-visualisations"><strong>4 Exploratory Data Analysis and Statistical Visualisations</strong></a>
  <ul>
  <li><a href="#gender-age-group-and-heart-attack-occurrence" id="toc-gender-age-group-and-heart-attack-occurrence" class="nav-link" data-scroll-target="#gender-age-group-and-heart-attack-occurrence"><strong>4.1 Gender, Age Group and Heart Attack Occurrence</strong></a></li>
  </ul></li>
  <li><a href="#bmi-and-heart-attack-occurrrence" id="toc-bmi-and-heart-attack-occurrrence" class="nav-link" data-scroll-target="#bmi-and-heart-attack-occurrrence"><strong>4.2 BMI and Heart Attack Occurrrence</strong></a>
  <ul>
  <li><a href="#association-of-heart-attack-with-hypertension-and-cholesterol" id="toc-association-of-heart-attack-with-hypertension-and-cholesterol" class="nav-link" data-scroll-target="#association-of-heart-attack-with-hypertension-and-cholesterol"><strong>4.3 Association of Heart Attack with Hypertension and Cholesterol</strong></a></li>
  <li><a href="#association-of-heart-attack-with-medical-history" id="toc-association-of-heart-attack-with-medical-history" class="nav-link" data-scroll-target="#association-of-heart-attack-with-medical-history"><strong>4.4 Association of Heart Attack with Medical History</strong></a></li>
  <li><a href="#lifestyle-factors-and-heart-attack-occurrence" id="toc-lifestyle-factors-and-heart-attack-occurrence" class="nav-link" data-scroll-target="#lifestyle-factors-and-heart-attack-occurrence"><strong>4.5 Lifestyle Factors and Heart Attack Occurrence</strong></a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><strong>5 Conclusion</strong></a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><strong>6 References</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Moo Jia Rong </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 1, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">February 9, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="overview" class="level3">
<h3 class="anchored" data-anchor-id="overview"><strong>1 Overview</strong></h3>
<section id="background" class="level4">
<h4 class="anchored" data-anchor-id="background"><strong>1.1 Background</strong></h4>
<p>Heart attack is one of the leading causes of mortality globally. According to findings of <a href="https://www.sciencedaily.com/releases/2019/03/190307081026.htm">research studies</a>, heart attacks are increasingly common in young adults (aged 40 or below). The alarming trend highlights a need to understand the potential causes and risk factors of early heart attacks through examining the profiles of young adult and older adult patients, including demographic, lifestyle factors and medical history, to enable early detection and enforcement of preventive measures.</p>
</section>
<section id="dataset" class="level4">
<h4 class="anchored" data-anchor-id="dataset"><strong>1.2 Dataset</strong></h4>
<p>In this exercise, we have obtained a dataset on heart attack incidents in Japan from <a href="https://www.kaggle.com/datasets/ashaychoudhary/heart-attack-in-japan-youth-vs-adult">Kaggle</a>, consisting of data on individuals aged 18 to 79.</p>
</section>
<section id="objectives" class="level4">
<h4 class="anchored" data-anchor-id="objectives"><strong>1.3 Objectives</strong></h4>
<p>As part of an international media company that publishes weekly content on digital platforms, we will Use the Japan heart attack dataset to perform Exploratory Data Analysis and generate statistical visualisations for an article, covering insights on:</p>
<ol type="1">
<li>The general profile of Japan population</li>
<li>Trends and associations of heart attack occurrence with demographic, lifestyle factors and medical history in the Japan populations.</li>
<li>Age-specific factors for heart attack occurrence</li>
</ol>
</section>
</section>
<section id="getting-started" class="level3">
<h3 class="anchored" data-anchor-id="getting-started"><strong>2 Getting Started</strong></h3>
<section id="loading-packages" class="level4">
<h4 class="anchored" data-anchor-id="loading-packages"><strong>2.1 Loading Packages</strong></h4>
<p>The R packages used in this exercise includes:</p>
<ul>
<li>tidyverse (i.e.&nbsp;readr, tidyr, dplyr, ggplot2) for performing data science tasks such as importing, tidying, and wrangling data, as well as creating graphs</li>
<li>knitr for displaying tables</li>
<li>patchwork for preparing composite figure created using ggplot2</li>
<li>ggstats for creating diverging barplots</li>
<li>ggdist for visualising distributions and uncertainty</li>
<li>ggmosaic for creating mosaic plots</li>
<li>ggstatsplot for visualising significant test of association using stacked barplots</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse,knitr, patchwork,ggstats, ggdist,ggmosaic, ggstatsplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-data" class="level4">
<h4 class="anchored" data-anchor-id="importing-data"><strong>2.2 Importing Data</strong></h4>
<p>The dataset used in this exercise is the <em>japan_heart_attack_dataset.csv</em> file downloaded from Kaggle. The file is imported into R environment using <code>read_csv()</code>.</p>
<p>Using the <code>glimpse()</code> function, we observe that the dataset consists of 30,000 records spanning across 32 columns. Of which, there are 17 relevant variables and 15 extra column variables which are irrelevant to our analysis.</p>
<p>In addition, by viewing the first few entries of each column, we can see that there are both categorical and continuous variables in the dataset.</p>
<p>With a focus on the 17 relevant variables, a data dictionary table is generated, showing the range for the 7 continuous variables and the unique values for the 10 categorical variables.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Import data</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Glimpse data</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Data dictionary</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>heart_attack <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/japan_heart_attack_dataset.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">glimpse</span>(heart_attack)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 30,000
Columns: 32
$ Age                     &lt;dbl&gt; 56, 69, 46, 32, 60, 25, 78, 38, 56, 75, 36, 40…
$ Gender                  &lt;chr&gt; "Male", "Male", "Male", "Female", "Female", "F…
$ Region                  &lt;chr&gt; "Urban", "Urban", "Rural", "Urban", "Rural", "…
$ Smoking_History         &lt;chr&gt; "Yes", "No", "Yes", "No", "No", "No", "No", "Y…
$ Diabetes_History        &lt;chr&gt; "No", "No", "No", "No", "No", "No", "Yes", "No…
$ Hypertension_History    &lt;chr&gt; "No", "No", "No", "No", "No", "No", "Yes", "No…
$ Cholesterol_Level       &lt;dbl&gt; 186.4002, 185.1367, 210.6966, 211.1655, 223.81…
$ Physical_Activity       &lt;chr&gt; "Moderate", "Low", "Low", "Moderate", "High", …
$ Diet_Quality            &lt;chr&gt; "Poor", "Good", "Average", "Good", "Good", "Go…
$ Alcohol_Consumption     &lt;chr&gt; "Low", "Low", "Moderate", "High", "High", "Hig…
$ Stress_Levels           &lt;dbl&gt; 3.644786, 3.384056, 3.810911, 6.014878, 6.8068…
$ BMI                     &lt;dbl&gt; 33.96135, 28.24287, 27.60121, 23.71729, 19.771…
$ Heart_Rate              &lt;dbl&gt; 72.30153, 57.45764, 64.65870, 55.13147, 76.667…
$ Systolic_BP             &lt;dbl&gt; 123.90209, 129.89331, 145.65490, 131.78522, 10…
$ Diastolic_BP            &lt;dbl&gt; 85.68281, 73.52426, 71.99481, 68.21133, 92.902…
$ Family_History          &lt;chr&gt; "No", "Yes", "No", "No", "No", "No", "No", "No…
$ Heart_Attack_Occurrence &lt;chr&gt; "No", "No", "No", "No", "No", "No", "No", "No"…
$ Extra_Column_1          &lt;dbl&gt; 0.40498852, 0.03627815, 0.85297888, 0.39085280…
$ Extra_Column_2          &lt;dbl&gt; 0.43330004, 0.51256694, 0.21959083, 0.29684675…
$ Extra_Column_3          &lt;dbl&gt; 0.62871236, 0.66839275, 0.61343656, 0.15572404…
$ Extra_Column_4          &lt;dbl&gt; 0.70160955, 0.11552874, 0.50800995, 0.87025144…
$ Extra_Column_5          &lt;dbl&gt; 0.49814235, 0.42381938, 0.90066981, 0.39035591…
$ Extra_Column_6          &lt;dbl&gt; 0.007901312, 0.083932768, 0.227205241, 0.40318…
$ Extra_Column_7          &lt;dbl&gt; 0.79458257, 0.68895108, 0.49634358, 0.74140891…
$ Extra_Column_8          &lt;dbl&gt; 0.29077922, 0.83016364, 0.75210679, 0.22396813…
$ Extra_Column_9          &lt;dbl&gt; 0.49719307, 0.63449028, 0.18150125, 0.32931387…
$ Extra_Column_10         &lt;dbl&gt; 0.52199452, 0.30204337, 0.62918031, 0.14319054…
$ Extra_Column_11         &lt;dbl&gt; 0.79965663, 0.04368285, 0.01827617, 0.90778075…
$ Extra_Column_12         &lt;dbl&gt; 0.72239788, 0.45166789, 0.06322702, 0.54232201…
$ Extra_Column_13         &lt;dbl&gt; 0.1487387, 0.8786714, 0.1465122, 0.9224606, 0.…
$ Extra_Column_14         &lt;dbl&gt; 0.8340099, 0.5356022, 0.9972962, 0.6262165, 0.…
$ Extra_Column_15         &lt;dbl&gt; 0.061632229, 0.617825340, 0.974455410, 0.22860…</code></pre>
</div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>data_dict <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">matrix</span>(<span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">nrow =</span> <span class="dv">0</span>))</span>
<span id="cb5-2"><a href="#cb5-2"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Variable"</span>, <span class="st">"Type"</span>, <span class="st">"Values"</span>)</span>
<span id="cb5-3"><a href="#cb5-3"></a><span class="fu">colnames</span>(data_dict) <span class="ot">&lt;-</span> x</span>
<span id="cb5-4"><a href="#cb5-4"></a></span>
<span id="cb5-5"><a href="#cb5-5"></a>column_names <span class="ot">&lt;-</span> <span class="fu">colnames</span>(heart_attack)[<span class="dv">1</span><span class="sc">:</span><span class="dv">17</span>]</span>
<span id="cb5-6"><a href="#cb5-6"></a><span class="cf">for</span> (column <span class="cf">in</span> column_names){</span>
<span id="cb5-7"><a href="#cb5-7"></a>  values <span class="ot">&lt;-</span> heart_attack[, column]</span>
<span id="cb5-8"><a href="#cb5-8"></a>  <span class="cf">if</span> (<span class="fu">class</span>(heart_attack[[column]])<span class="sc">==</span><span class="st">"numeric"</span>){</span>
<span id="cb5-9"><a href="#cb5-9"></a>    col_label<span class="ot">&lt;-</span><span class="fu">paste0</span>(<span class="st">"("</span>, <span class="fu">round</span>(<span class="fu">min</span>(values), <span class="at">digits=</span><span class="dv">2</span>), <span class="st">", "</span>, <span class="fu">round</span>(<span class="fu">max</span>(values), <span class="at">digits=</span><span class="dv">2</span>), <span class="st">")"</span>)</span>
<span id="cb5-10"><a href="#cb5-10"></a>    col_type<span class="ot">=</span><span class="st">"Continuous"</span></span>
<span id="cb5-11"><a href="#cb5-11"></a>  }</span>
<span id="cb5-12"><a href="#cb5-12"></a>  <span class="cf">else</span> {</span>
<span id="cb5-13"><a href="#cb5-13"></a>    col_label<span class="ot">&lt;-</span><span class="fu">paste0</span>(<span class="fu">unique</span>(values))</span>
<span id="cb5-14"><a href="#cb5-14"></a>    col_type<span class="ot">=</span><span class="st">"Categorical"</span></span>
<span id="cb5-15"><a href="#cb5-15"></a>  }</span>
<span id="cb5-16"><a href="#cb5-16"></a>  new.row <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Variable =</span> column, <span class="at">Type =</span> col_type , <span class="at">Values =</span> col_label)</span>
<span id="cb5-17"><a href="#cb5-17"></a>  data_dict <span class="ot">&lt;-</span> <span class="fu">rbind</span>(data_dict, new.row)</span>
<span id="cb5-18"><a href="#cb5-18"></a>  </span>
<span id="cb5-19"><a href="#cb5-19"></a>}</span>
<span id="cb5-20"><a href="#cb5-20"></a></span>
<span id="cb5-21"><a href="#cb5-21"></a>data_dict[<span class="st">"Description"</span>]<span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">""</span>,<span class="st">""</span>,<span class="st">""</span>,<span class="st">""</span>,<span class="st">""</span>, <span class="st">"Patient hypertension ( high blood pressure) history</span></span>
<span id="cb5-22"><a href="#cb5-22"></a><span class="st">"</span>, <span class="st">"normal total cholesterol level (mg/dL) &lt; 200 </span></span>
<span id="cb5-23"><a href="#cb5-23"></a><span class="st">"</span>, <span class="st">""</span>,<span class="st">""</span>,<span class="st">""</span>,<span class="st">""</span>, <span class="st">"Healthy BMI range is 18.5 to 24.9</span></span>
<span id="cb5-24"><a href="#cb5-24"></a><span class="st">"</span>, <span class="st">""</span>, <span class="st">"Normal systolic  blood pressure (mmHg) &lt;120 </span></span>
<span id="cb5-25"><a href="#cb5-25"></a><span class="st">"</span>, <span class="st">"Normal diastolic  blood pressure (mmHg) &lt;80</span></span>
<span id="cb5-26"><a href="#cb5-26"></a><span class="st">"</span>, <span class="st">""</span>,<span class="st">""</span>)</span>
<span id="cb5-27"><a href="#cb5-27"></a></span>
<span id="cb5-28"><a href="#cb5-28"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(data_dict, <span class="st">"html"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Type</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Values</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">(18, 79)</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Gender</td>
<td style="text-align: left;">Categorical</td>
<td style="text-align: left;">c("Male", "Female")</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Region</td>
<td style="text-align: left;">Categorical</td>
<td style="text-align: left;">c("Urban", "Rural")</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Smoking_History</td>
<td style="text-align: left;">Categorical</td>
<td style="text-align: left;">c("Yes", "No")</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diabetes_History</td>
<td style="text-align: left;">Categorical</td>
<td style="text-align: left;">c("No", "Yes")</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Hypertension_History</td>
<td style="text-align: left;">Categorical</td>
<td style="text-align: left;">c("No", "Yes")</td>
<td style="text-align: left;">Patient hypertension ( high blood pressure) history</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cholesterol_Level</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">(80.02, 336.86)</td>
<td style="text-align: left;">normal total cholesterol level (mg/dL) &lt; 200</td>
</tr>
<tr class="even">
<td style="text-align: left;">Physical_Activity</td>
<td style="text-align: left;">Categorical</td>
<td style="text-align: left;">c("Moderate", "Low", "High")</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diet_Quality</td>
<td style="text-align: left;">Categorical</td>
<td style="text-align: left;">c("Poor", "Good", "Average")</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Alcohol_Consumption</td>
<td style="text-align: left;">Categorical</td>
<td style="text-align: left;">c("Low", "Moderate", "High", "None")</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stress_Levels</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">(0, 10)</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">BMI</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">(5.58, 46.1)</td>
<td style="text-align: left;">Healthy BMI range is 18.5 to 24.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heart_Rate</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">(30.03, 108.78)</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Systolic_BP</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">(56.23, 178.77)</td>
<td style="text-align: left;">Normal systolic blood pressure (mmHg) &lt;120</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diastolic_BP</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">(39.95, 117.67)</td>
<td style="text-align: left;">Normal diastolic blood pressure (mmHg) &lt;80</td>
</tr>
<tr class="even">
<td style="text-align: left;">Family_History</td>
<td style="text-align: left;">Categorical</td>
<td style="text-align: left;">c("No", "Yes")</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heart_Attack_Occurrence</td>
<td style="text-align: left;">Categorical</td>
<td style="text-align: left;">c("No", "Yes")</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="data-wrangling" class="level3">
<h3 class="anchored" data-anchor-id="data-wrangling"><strong>3 Data Wrangling</strong></h3>
<section id="removing-irrelevant-data" class="level4">
<h4 class="anchored" data-anchor-id="removing-irrelevant-data"><strong>3.1 Removing irrelevant data</strong></h4>
<p>We first remove the 15 ‘extra columns’ in the dataset, which are irrelvant for our analysis, using the code below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>df<span class="ot">&lt;-</span>heart_attack[, <span class="dv">1</span><span class="sc">:</span><span class="dv">17</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This leaves us with just 17 variables:</p>
<p><u>General Demographic Variables</u></p>
<ul>
<li>Age</li>
<li>Gender</li>
<li>Region</li>
<li>BMI</li>
</ul>
<p><u>Lifestyle Factors</u></p>
<ul>
<li>Smoking_History</li>
<li>Physical_Activity</li>
<li>Diet_Quality</li>
<li>Alcohol_Consumption</li>
<li>Stress_Levels</li>
</ul>
<p><u>Medical History</u></p>
<ul>
<li>Diabetes_History</li>
<li>Hypertension_History</li>
<li>Cholesterol_Level</li>
<li>Heart_Rate</li>
<li>Systolic_BP</li>
<li>Diastolic_BP</li>
<li>Family_History</li>
<li>Heart_Attack_Occurrence</li>
</ul>
</section>
<section id="check-for-duplicated-or-missing-values" class="level4">
<h4 class="anchored" data-anchor-id="check-for-duplicated-or-missing-values"><strong>3.2 Check for duplicated or missing values</strong></h4>
<p>Next, the <code>duplicated()</code> and <code>is.na()</code> functions are used to check for duplicate records and missing values in the dataset respectively.</p>
<p>There are no duplicated records or missing values in this dataset.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Duplicated records</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Missing values</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>df[<span class="fu">duplicated</span>(df),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 17
# ℹ 17 variables: Age &lt;dbl&gt;, Gender &lt;chr&gt;, Region &lt;chr&gt;, Smoking_History &lt;chr&gt;,
#   Diabetes_History &lt;chr&gt;, Hypertension_History &lt;chr&gt;,
#   Cholesterol_Level &lt;dbl&gt;, Physical_Activity &lt;chr&gt;, Diet_Quality &lt;chr&gt;,
#   Alcohol_Consumption &lt;chr&gt;, Stress_Levels &lt;dbl&gt;, BMI &lt;dbl&gt;,
#   Heart_Rate &lt;dbl&gt;, Systolic_BP &lt;dbl&gt;, Diastolic_BP &lt;dbl&gt;,
#   Family_History &lt;chr&gt;, Heart_Attack_Occurrence &lt;chr&gt;</code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="recode-age" class="level4">
<h4 class="anchored" data-anchor-id="recode-age"><strong>3.3 Recode Age</strong></h4>
<p>The age distribution in the population is shown in the histogram below. There is a relatively even spread of records from young to old.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(Age)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, </span>
<span id="cb11-3"><a href="#cb11-3"></a>                 <span class="at">boundary =</span> <span class="dv">100</span>,</span>
<span id="cb11-4"><a href="#cb11-4"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb11-5"><a href="#cb11-5"></a>                 <span class="at">fill=</span><span class="st">"#7F948F"</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Frequency of Age"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To facilitate comparison of profiles of younger versus older heart attack patients, we can create a new variable named <em>Age_Group</em> to bin the records into different age groups using <code>ifelse</code> statements:</p>
<ol type="1">
<li>Young Adults: 18-39</li>
<li>Middle-aged Adults: 40-65</li>
<li>Old Adults: 66-79</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>df<span class="sc">$</span>Age_Groups <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>Age<span class="sc">&lt;=</span><span class="dv">35</span>, <span class="st">"Young"</span>, <span class="fu">ifelse</span>(df<span class="sc">$</span>Age<span class="sc">&lt;=</span><span class="dv">65</span>, <span class="st">"Middle-aged"</span>, <span class="st">"Old"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="recode-bmi" class="level4">
<h4 class="anchored" data-anchor-id="recode-bmi"><strong>3.4 Recode BMI</strong></h4>
<p>The BMI distribution in the population is shown in the histogram below. We can observe that the BMI distribution resembles a normal distribution and about half of the population has BMI &gt; 25, which is above the healthy range. For better comparisons in our analyses, we should bin BMI.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(BMI)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2"></a>  <span class="fu">geom_histogram</span>(<span class="at">boundary =</span> <span class="dv">100</span>,</span>
<span id="cb13-3"><a href="#cb13-3"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb13-4"><a href="#cb13-4"></a>                 <span class="at">fill=</span><span class="st">"#7F948F"</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Frequency of BMI"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>BMI can be further categorised according to the criterion below, according to definition by Centers for Disease Control and Prevention:</p>
<ul>
<li>Underweight: &lt;18.5</li>
<li>Normal: 18.5 to &lt;25</li>
<li>Overweight: 25 to &lt;30</li>
<li>Obese: ≥30</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>df<span class="sc">$</span>BMI_Category <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>BMI<span class="sc">&lt;</span><span class="fl">18.5</span>, <span class="st">"Underweight"</span>, </span>
<span id="cb14-2"><a href="#cb14-2"></a>                          <span class="fu">ifelse</span>(df<span class="sc">$</span>BMI<span class="sc">&lt;</span><span class="dv">25</span>, <span class="st">"Normal"</span>, </span>
<span id="cb14-3"><a href="#cb14-3"></a>                                 <span class="fu">ifelse</span>(df<span class="sc">$</span>BMI<span class="sc">&lt;</span><span class="dv">30</span>, <span class="st">"Overweight"</span>, <span class="st">"Obese"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="creating-blood-pressure-variable" class="level4">
<h4 class="anchored" data-anchor-id="creating-blood-pressure-variable"><strong>3.5 Creating blood pressure variable</strong></h4>
<p>As the dataset provides the Systolic and Diastolic Blood Pressures, we can use these information to further categorise the population based on their blood pressure category, according to the criterion shown in the figure below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-3164247285.png" class="img-fluid figure-img"></p>
<figcaption>Source: American Heart Association</figcaption>
</figure>
</div>
<p>The distribution of the Systolic and Diastolic blood pressures are shown in the figure below. There are no records with hypertensive crisis (Systolic BP &gt; 180 mmHg or Diastolic BP &gt; 120 mmHg). Therefore, we will only have 4 blood pressure groups: Normal, Elevated, Hypertension I and Hypertension II.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a>p1<span class="ot">&lt;-</span><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(Systolic_BP)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>,</span>
<span id="cb15-3"><a href="#cb15-3"></a>                 <span class="at">boundary =</span> <span class="dv">100</span>,</span>
<span id="cb15-4"><a href="#cb15-4"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb15-5"><a href="#cb15-5"></a>                 <span class="at">fill=</span><span class="st">"thistle"</span>) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">n.breaks =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Frequency of Systolic BP"</span>) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8"></a>  <span class="fu">xlab</span>(<span class="st">"Systolic BP (mmHg)"</span>)</span>
<span id="cb15-9"><a href="#cb15-9"></a></span>
<span id="cb15-10"><a href="#cb15-10"></a>p2<span class="ot">&lt;-</span><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(Diastolic_BP)) <span class="sc">+</span></span>
<span id="cb15-11"><a href="#cb15-11"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>,</span>
<span id="cb15-12"><a href="#cb15-12"></a>                 <span class="at">boundary =</span> <span class="dv">100</span>,</span>
<span id="cb15-13"><a href="#cb15-13"></a>                 <span class="at">color=</span><span class="st">"black"</span>, </span>
<span id="cb15-14"><a href="#cb15-14"></a>                 <span class="at">fill=</span><span class="st">"lightsteelblue"</span>) <span class="sc">+</span></span>
<span id="cb15-15"><a href="#cb15-15"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Frequency of Diastolic BP"</span>)<span class="sc">+</span></span>
<span id="cb15-16"><a href="#cb15-16"></a>  <span class="fu">xlab</span>(<span class="st">"Diastolic BP (mmHg)"</span>)</span>
<span id="cb15-17"><a href="#cb15-17"></a></span>
<span id="cb15-18"><a href="#cb15-18"></a>p1 <span class="sc">+</span> p2 <span class="sc">+</span> <span class="fu">plot_annotation</span>(<span class="at">tag_levels =</span> <span class="st">'I'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>df<span class="sc">$</span>Blood_Pressure <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>Systolic_BP<span class="sc">&lt;</span><span class="dv">120</span> <span class="sc">&amp;</span> df<span class="sc">$</span>Diastolic_BP<span class="sc">&lt;</span><span class="dv">80</span>, <span class="st">"Normal"</span>, </span>
<span id="cb16-2"><a href="#cb16-2"></a>                            <span class="fu">ifelse</span>(df<span class="sc">$</span>Systolic_BP<span class="sc">&lt;</span><span class="dv">130</span> <span class="sc">&amp;</span> df<span class="sc">$</span>Diastolic_BP<span class="sc">&lt;</span><span class="dv">80</span>, <span class="st">"Elevated"</span>, </span>
<span id="cb16-3"><a href="#cb16-3"></a>                                   <span class="fu">ifelse</span>((df<span class="sc">$</span>Systolic_BP<span class="sc">&gt;=</span><span class="dv">130</span> <span class="sc">&amp;</span> df<span class="sc">$</span>Systolic_BP<span class="sc">&lt;</span><span class="dv">140</span>)<span class="sc">|</span></span>
<span id="cb16-4"><a href="#cb16-4"></a>                                            ( df<span class="sc">$</span>Diastolic_BP<span class="sc">&lt;</span><span class="dv">90</span> <span class="sc">&amp;</span> df<span class="sc">$</span>Diastolic_BP<span class="sc">&gt;=</span><span class="dv">80</span>), <span class="st">"Hypertension I"</span>, <span class="st">"Hypertension II"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="recode-cholesterol-level" class="level4">
<h4 class="anchored" data-anchor-id="recode-cholesterol-level"><strong>3.6 Recode Cholesterol Level</strong></h4>
<p>Total Cholesterol Level can also be further categorised according to the criterion below:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-3010395143.png" class="img-fluid figure-img"></p>
<figcaption>Source: Singapore Heart Foundation</figcaption>
</figure>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>df<span class="sc">$</span>Cholesterol_Category <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>Cholesterol_Level<span class="sc">&lt;</span><span class="dv">200</span>, <span class="st">"Normal"</span>, <span class="fu">ifelse</span>(df<span class="sc">$</span>Cholesterol_Level<span class="sc">&lt;</span><span class="dv">240</span>, <span class="st">"Borderline High"</span>, <span class="st">"High"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="ordering-levels-for-ordinal-categorical-variables" class="level4">
<h4 class="anchored" data-anchor-id="ordering-levels-for-ordinal-categorical-variables"><strong>3.7 Ordering levels for ordinal categorical variables</strong></h4>
<p>For ordinal categorical variables, we will order the different levels in an ascending order using <code>factor()</code>, so that the results will be displayed according to the order we have set in the graphs we will plot subsequently in our analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>df<span class="sc">$</span>Physical_Activity <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>Physical_Activity, </span>
<span id="cb18-2"><a href="#cb18-2"></a>                               <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Moderate"</span>, <span class="st">"High"</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span> )</span>
<span id="cb18-3"><a href="#cb18-3"></a></span>
<span id="cb18-4"><a href="#cb18-4"></a>df<span class="sc">$</span>Diet_Quality <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>Diet_Quality, </span>
<span id="cb18-5"><a href="#cb18-5"></a>                          <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Poor"</span>, <span class="st">"Average"</span>, <span class="st">"Good"</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-6"><a href="#cb18-6"></a></span>
<span id="cb18-7"><a href="#cb18-7"></a>df<span class="sc">$</span>Alcohol_Consumption <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>Alcohol_Consumption, </span>
<span id="cb18-8"><a href="#cb18-8"></a>                                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"None"</span>, <span class="st">"Low"</span>, <span class="st">"Moderate"</span>, <span class="st">"High"</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-9"><a href="#cb18-9"></a></span>
<span id="cb18-10"><a href="#cb18-10"></a>df<span class="sc">$</span>Age_Groups <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>Age_Groups, </span>
<span id="cb18-11"><a href="#cb18-11"></a>                                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Young"</span>, <span class="st">"Middle-aged"</span>, <span class="st">"Old"</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-12"><a href="#cb18-12"></a></span>
<span id="cb18-13"><a href="#cb18-13"></a>df<span class="sc">$</span>BMI_Category <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>BMI_Category, </span>
<span id="cb18-14"><a href="#cb18-14"></a>                                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Underweight"</span>, <span class="st">"Normal"</span>, <span class="st">"Overweight"</span>, <span class="st">"Obese"</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-15"><a href="#cb18-15"></a></span>
<span id="cb18-16"><a href="#cb18-16"></a>df<span class="sc">$</span>Blood_Pressure <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>Blood_Pressure, </span>
<span id="cb18-17"><a href="#cb18-17"></a>                                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Elevated"</span>, <span class="st">"Hypertension I"</span>, <span class="st">"Hypertension II"</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-18"><a href="#cb18-18"></a></span>
<span id="cb18-19"><a href="#cb18-19"></a>df<span class="sc">$</span>Cholesterol_Category <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>Cholesterol_Category, </span>
<span id="cb18-20"><a href="#cb18-20"></a>                                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Borderline High"</span>, <span class="st">"High"</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The first 5 results of the final dataset are displayed below using <code>kable()</code> of the knitr package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(df, <span class="at">n=</span><span class="dv">5</span>), <span class="at">caption =</span> <span class="st">"Heart Attack in Japan"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Heart Attack in Japan</caption>
<colgroup>
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Age</th>
<th style="text-align: left;">Gender</th>
<th style="text-align: left;">Region</th>
<th style="text-align: left;">Smoking_History</th>
<th style="text-align: left;">Diabetes_History</th>
<th style="text-align: left;">Hypertension_History</th>
<th style="text-align: right;">Cholesterol_Level</th>
<th style="text-align: left;">Physical_Activity</th>
<th style="text-align: left;">Diet_Quality</th>
<th style="text-align: left;">Alcohol_Consumption</th>
<th style="text-align: right;">Stress_Levels</th>
<th style="text-align: right;">BMI</th>
<th style="text-align: right;">Heart_Rate</th>
<th style="text-align: right;">Systolic_BP</th>
<th style="text-align: right;">Diastolic_BP</th>
<th style="text-align: left;">Family_History</th>
<th style="text-align: left;">Heart_Attack_Occurrence</th>
<th style="text-align: left;">Age_Groups</th>
<th style="text-align: left;">BMI_Category</th>
<th style="text-align: left;">Blood_Pressure</th>
<th style="text-align: left;">Cholesterol_Category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">56</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">186.4002</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Poor</td>
<td style="text-align: left;">Low</td>
<td style="text-align: right;">3.644786</td>
<td style="text-align: right;">33.96135</td>
<td style="text-align: right;">72.30153</td>
<td style="text-align: right;">123.9021</td>
<td style="text-align: right;">85.68281</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Middle-aged</td>
<td style="text-align: left;">Obese</td>
<td style="text-align: left;">Hypertension I</td>
<td style="text-align: left;">Normal</td>
</tr>
<tr class="even">
<td style="text-align: right;">69</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">185.1367</td>
<td style="text-align: left;">Low</td>
<td style="text-align: left;">Good</td>
<td style="text-align: left;">Low</td>
<td style="text-align: right;">3.384056</td>
<td style="text-align: right;">28.24287</td>
<td style="text-align: right;">57.45764</td>
<td style="text-align: right;">129.8933</td>
<td style="text-align: right;">73.52426</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Old</td>
<td style="text-align: left;">Overweight</td>
<td style="text-align: left;">Elevated</td>
<td style="text-align: left;">Normal</td>
</tr>
<tr class="odd">
<td style="text-align: right;">46</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">210.6966</td>
<td style="text-align: left;">Low</td>
<td style="text-align: left;">Average</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: right;">3.810911</td>
<td style="text-align: right;">27.60121</td>
<td style="text-align: right;">64.65870</td>
<td style="text-align: right;">145.6549</td>
<td style="text-align: right;">71.99481</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Middle-aged</td>
<td style="text-align: left;">Overweight</td>
<td style="text-align: left;">Hypertension II</td>
<td style="text-align: left;">Borderline High</td>
</tr>
<tr class="even">
<td style="text-align: right;">32</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Urban</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">211.1655</td>
<td style="text-align: left;">Moderate</td>
<td style="text-align: left;">Good</td>
<td style="text-align: left;">High</td>
<td style="text-align: right;">6.014878</td>
<td style="text-align: right;">23.71729</td>
<td style="text-align: right;">55.13147</td>
<td style="text-align: right;">131.7852</td>
<td style="text-align: right;">68.21133</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Young</td>
<td style="text-align: left;">Normal</td>
<td style="text-align: left;">Hypertension I</td>
<td style="text-align: left;">Borderline High</td>
</tr>
<tr class="odd">
<td style="text-align: right;">60</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Rural</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">223.8143</td>
<td style="text-align: left;">High</td>
<td style="text-align: left;">Good</td>
<td style="text-align: left;">High</td>
<td style="text-align: right;">6.806883</td>
<td style="text-align: right;">19.77158</td>
<td style="text-align: right;">76.66792</td>
<td style="text-align: right;">100.6946</td>
<td style="text-align: right;">92.90249</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Middle-aged</td>
<td style="text-align: left;">Normal</td>
<td style="text-align: left;">Hypertension II</td>
<td style="text-align: left;">Borderline High</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="exploratory-data-analysis-and-statistical-visualisations" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis-and-statistical-visualisations"><strong>4 Exploratory Data Analysis and Statistical Visualisations</strong></h3>
<p>In this section, we will be conducting Exploratory Data Analysis on the processed dataset named <em>df</em>.</p>
<p>Before diving into the analysis, we first take a look at the distribution of some of the key variables closely-linked to heart attack in the Japan population: Age group, Cholesterol Level, Blood Pressure, BMI category and heart attack occurrence.</p>
<p>The <code>ggplot()</code> and <code>geom_bar()</code> functions from the <em>ggplot2</em> package was used to generate the bar charts. <code>stat = 'count'</code> argument and <code>geom_text()</code> was used to add percentage annotations onto the bar chart. The bar chart colors were set using <code>scale_fill_manual()</code>. The axis labels were defined using <code>labs()</code>. The aesthetics of the bar charts were further customised using <code>theme()</code>. Individual plots were combined using <em>patchwork</em> package.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>p1<span class="ot">&lt;-</span><span class="fu">ggplot</span>(<span class="at">data=</span>df,<span class="fu">aes</span>(<span class="at">x=</span>Age_Groups, <span class="at">fill=</span>Age_Groups))<span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"count"</span>)<span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"lightsteelblue"</span>,<span class="st">"lightcyan3"</span>,<span class="st">"thistle"</span>))<span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb20-5"><a href="#cb20-5"></a>    <span class="fu">aes</span>(</span>
<span id="cb20-6"><a href="#cb20-6"></a>      <span class="at">label =</span> scales<span class="sc">::</span><span class="fu">percent</span>(..count..<span class="sc">/</span><span class="fu">sum</span>(..count..), <span class="at">accuracy =</span> <span class="fl">0.1</span>)  <span class="co"># Calculate percentage using sum of counts</span></span>
<span id="cb20-7"><a href="#cb20-7"></a>    ),</span>
<span id="cb20-8"><a href="#cb20-8"></a>    <span class="at">stat =</span> <span class="st">"count"</span>,</span>
<span id="cb20-9"><a href="#cb20-9"></a>    <span class="at">vjust =</span> <span class="fl">1.25</span>,  <span class="co"># Adjust text placement </span></span>
<span id="cb20-10"><a href="#cb20-10"></a>    <span class="at">size=</span><span class="dv">3</span></span>
<span id="cb20-11"><a href="#cb20-11"></a>  ) <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12"></a>  <span class="fu">theme</span>(<span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(), <span class="at">legend.position =</span> <span class="st">"None"</span>)<span class="sc">+</span></span>
<span id="cb20-13"><a href="#cb20-13"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age Group"</span>)</span>
<span id="cb20-14"><a href="#cb20-14"></a></span>
<span id="cb20-15"><a href="#cb20-15"></a>p2<span class="ot">&lt;-</span><span class="fu">ggplot</span>(<span class="at">data=</span>df,<span class="fu">aes</span>(<span class="at">x=</span>Blood_Pressure, <span class="at">fill=</span>Blood_Pressure))<span class="sc">+</span></span>
<span id="cb20-16"><a href="#cb20-16"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"count"</span>)<span class="sc">+</span></span>
<span id="cb20-17"><a href="#cb20-17"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"lightsteelblue"</span>,<span class="st">"lightcyan3"</span>,<span class="st">"thistle"</span>,<span class="st">"rosybrown2"</span> ))<span class="sc">+</span></span>
<span id="cb20-18"><a href="#cb20-18"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb20-19"><a href="#cb20-19"></a>    <span class="fu">aes</span>(</span>
<span id="cb20-20"><a href="#cb20-20"></a>      <span class="at">label =</span> scales<span class="sc">::</span><span class="fu">percent</span>(..count..<span class="sc">/</span><span class="fu">sum</span>(..count..), <span class="at">accuracy =</span> <span class="fl">0.1</span>)  <span class="co"># Calculate percentage using sum of counts</span></span>
<span id="cb20-21"><a href="#cb20-21"></a>    ),</span>
<span id="cb20-22"><a href="#cb20-22"></a>    <span class="at">stat =</span> <span class="st">"count"</span>,</span>
<span id="cb20-23"><a href="#cb20-23"></a>    <span class="at">vjust =</span> <span class="fl">1.25</span>,  <span class="co"># Adjust text placement </span></span>
<span id="cb20-24"><a href="#cb20-24"></a>    <span class="at">size=</span><span class="dv">3</span></span>
<span id="cb20-25"><a href="#cb20-25"></a>  ) <span class="sc">+</span></span>
<span id="cb20-26"><a href="#cb20-26"></a>  <span class="fu">theme</span>( <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(), <span class="at">legend.position =</span> <span class="st">"None"</span> )<span class="sc">+</span></span>
<span id="cb20-27"><a href="#cb20-27"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Blood Pressure"</span>)</span>
<span id="cb20-28"><a href="#cb20-28"></a></span>
<span id="cb20-29"><a href="#cb20-29"></a>p3<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>df,<span class="fu">aes</span>(<span class="at">x=</span>Heart_Attack_Occurrence, <span class="at">fill=</span>Heart_Attack_Occurrence))<span class="sc">+</span></span>
<span id="cb20-30"><a href="#cb20-30"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"count"</span>)<span class="sc">+</span></span>
<span id="cb20-31"><a href="#cb20-31"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"lightsteelblue"</span>,<span class="st">"thistle"</span> ))<span class="sc">+</span></span>
<span id="cb20-32"><a href="#cb20-32"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb20-33"><a href="#cb20-33"></a>    <span class="fu">aes</span>(</span>
<span id="cb20-34"><a href="#cb20-34"></a>      <span class="at">label =</span> scales<span class="sc">::</span><span class="fu">percent</span>(..count..<span class="sc">/</span><span class="fu">sum</span>(..count..), <span class="at">accuracy =</span> <span class="fl">0.1</span>)  <span class="co"># Calculate percentage using sum of counts</span></span>
<span id="cb20-35"><a href="#cb20-35"></a>    ),</span>
<span id="cb20-36"><a href="#cb20-36"></a>    <span class="at">stat =</span> <span class="st">"count"</span>,</span>
<span id="cb20-37"><a href="#cb20-37"></a>    <span class="at">vjust =</span> <span class="fl">1.05</span>,  <span class="co"># Adjust text placement </span></span>
<span id="cb20-38"><a href="#cb20-38"></a>    <span class="at">size=</span><span class="dv">3</span></span>
<span id="cb20-39"><a href="#cb20-39"></a>  ) <span class="sc">+</span></span>
<span id="cb20-40"><a href="#cb20-40"></a>  <span class="fu">theme</span>( <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(), <span class="at">legend.position =</span> <span class="st">"None"</span> )<span class="sc">+</span></span>
<span id="cb20-41"><a href="#cb20-41"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Heart Attack Occurrence"</span>)</span>
<span id="cb20-42"><a href="#cb20-42"></a></span>
<span id="cb20-43"><a href="#cb20-43"></a>p4<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>df,<span class="fu">aes</span>(<span class="at">x=</span>BMI_Category, <span class="at">fill=</span>BMI_Category))<span class="sc">+</span></span>
<span id="cb20-44"><a href="#cb20-44"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"count"</span>)<span class="sc">+</span></span>
<span id="cb20-45"><a href="#cb20-45"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"lightsteelblue"</span>,<span class="st">"lightcyan3"</span>,<span class="st">"thistle"</span>,<span class="st">"rosybrown2"</span> ))<span class="sc">+</span></span>
<span id="cb20-46"><a href="#cb20-46"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb20-47"><a href="#cb20-47"></a>    <span class="fu">aes</span>(</span>
<span id="cb20-48"><a href="#cb20-48"></a>      <span class="at">label =</span> scales<span class="sc">::</span><span class="fu">percent</span>(..count..<span class="sc">/</span><span class="fu">sum</span>(..count..), <span class="at">accuracy =</span> <span class="fl">0.1</span>)  <span class="co"># Calculate percentage using sum of counts</span></span>
<span id="cb20-49"><a href="#cb20-49"></a>    ),</span>
<span id="cb20-50"><a href="#cb20-50"></a>    <span class="at">stat =</span> <span class="st">"count"</span>,</span>
<span id="cb20-51"><a href="#cb20-51"></a>    <span class="at">vjust =</span> <span class="fl">1.25</span>,  <span class="co"># Adjust text placement </span></span>
<span id="cb20-52"><a href="#cb20-52"></a>    <span class="at">size=</span><span class="dv">3</span></span>
<span id="cb20-53"><a href="#cb20-53"></a>  ) <span class="sc">+</span></span>
<span id="cb20-54"><a href="#cb20-54"></a>  <span class="fu">theme</span>( <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(), <span class="at">legend.position =</span> <span class="st">"None"</span> )<span class="sc">+</span></span>
<span id="cb20-55"><a href="#cb20-55"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"BMI Category"</span>, <span class="at">fill=</span><span class="st">"BMI"</span>)</span>
<span id="cb20-56"><a href="#cb20-56"></a></span>
<span id="cb20-57"><a href="#cb20-57"></a>p5<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>df,<span class="fu">aes</span>(<span class="at">x=</span>Cholesterol_Category, <span class="at">fill=</span>Cholesterol_Category))<span class="sc">+</span></span>
<span id="cb20-58"><a href="#cb20-58"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"count"</span>)<span class="sc">+</span></span>
<span id="cb20-59"><a href="#cb20-59"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"lightsteelblue"</span>,<span class="st">"lightcyan3"</span>,<span class="st">"thistle"</span>))<span class="sc">+</span></span>
<span id="cb20-60"><a href="#cb20-60"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb20-61"><a href="#cb20-61"></a>    <span class="fu">aes</span>(</span>
<span id="cb20-62"><a href="#cb20-62"></a>      <span class="at">label =</span> scales<span class="sc">::</span><span class="fu">percent</span>(..count..<span class="sc">/</span><span class="fu">sum</span>(..count..), <span class="at">accuracy =</span> <span class="fl">0.1</span>)  <span class="co"># Calculate percentage using sum of counts</span></span>
<span id="cb20-63"><a href="#cb20-63"></a>    ),</span>
<span id="cb20-64"><a href="#cb20-64"></a>    <span class="at">stat =</span> <span class="st">"count"</span>,</span>
<span id="cb20-65"><a href="#cb20-65"></a>    <span class="at">vjust =</span> <span class="fl">1.25</span>,  <span class="co"># Adjust text placement </span></span>
<span id="cb20-66"><a href="#cb20-66"></a>    <span class="at">size=</span><span class="dv">3</span></span>
<span id="cb20-67"><a href="#cb20-67"></a>  ) <span class="sc">+</span></span>
<span id="cb20-68"><a href="#cb20-68"></a>  <span class="fu">theme</span>(<span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(), <span class="at">legend.position =</span> <span class="st">"None"</span>)<span class="sc">+</span></span>
<span id="cb20-69"><a href="#cb20-69"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Cholesterol Level"</span>)</span>
<span id="cb20-70"><a href="#cb20-70"></a></span>
<span id="cb20-71"><a href="#cb20-71"></a>(p1<span class="sc">+</span>p5)<span class="sc">/</span>(p3<span class="sc">+</span>p4)<span class="sc">/</span>p2<span class="sc">+</span> <span class="fu">plot_annotation</span>(<span class="at">title=</span> <span class="st">"Overview of Japan Population Profile"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Insights
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The study population primarily consist of Middle-aged (40-65), followed by Young adults (18-39) and Old adults (&gt;65).</li>
<li>About 10% have experienced heart attack, indicating high prevalence of heart attack in Japan and underscores importance of addressing cardiovascular health.</li>
<li>Alarmingly, only 25.2% have normal blood pressure, with 62.6% suffering from hypertension. Prolonged hypertension is a well-documented contributor to cardiovascular diseases, including heart attacks and strokes.</li>
<li>Nearly half of the population (49.8%) are either overweight or obese, which is known to be a significant risk factor for heart attack occurrence and correlates with other comorbidities such as diabetes and high cholesterol, exacerbating health conditions.</li>
<li>Similarly, approximately half of the population have elevated cholesterol levels.</li>
<li>The high incidence of hypertension, overweight/obesity and high cholesterol highlights a need for targeted public health campaigns to increase awareness to promote healthy lifestyles and targeted preventive measures.</li>
</ul>
</div>
</div>
<section id="gender-age-group-and-heart-attack-occurrence" class="level4">
<h4 class="anchored" data-anchor-id="gender-age-group-and-heart-attack-occurrence"><strong>4.1 Gender, Age Group and Heart Attack Occurrence</strong></h4>
<p>Next, we delve into bivariate analyses to understand correlation of heart attack with various factors. In this section, we will examine if biological factors like aging and gender are associated with heart attack. The figures below show the heart attack occurrence by Gender and Age Groups.</p>
<p>Mosaic plots were created using <code>geom_mosaic()</code> from the <em>ggmosaic</em> package and <code>ggplot()</code> from the <em>ggplot2</em> package. <code>labs()</code>, <code>theme()</code> and <code>scale_fill_manual</code> from <em>ggplot2</em> package were used to change the axis labels, theme and color of the graphs. <code>scale_y_continuous()</code> from <em>ggplot2</em> was used to display the percentages.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a>p1<span class="ot">&lt;-</span><span class="fu">ggplot</span>(df)<span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2"></a>    <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(Heart_Attack_Occurrence, Gender), <span class="at">fill=</span>Heart_Attack_Occurrence))<span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"#DF9999"</span>,<span class="st">"#99AEDF"</span>)) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4"></a>  <span class="fu">theme</span>( <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(), <span class="at">legend.position =</span> <span class="st">"bottom"</span> )<span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Gender"</span>, <span class="at">y=</span> <span class="st">"Heart Attack"</span>, <span class="at">fill=</span><span class="st">"Heart Attack"</span>)<span class="sc">+</span> </span>
<span id="cb21-6"><a href="#cb21-6"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent)</span>
<span id="cb21-7"><a href="#cb21-7"></a></span>
<span id="cb21-8"><a href="#cb21-8"></a>p2<span class="ot">&lt;-</span><span class="fu">ggplot</span>(df)<span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9"></a>    <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(Heart_Attack_Occurrence, Age_Groups), <span class="at">fill=</span>Heart_Attack_Occurrence))<span class="sc">+</span></span>
<span id="cb21-10"><a href="#cb21-10"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"lightsteelblue"</span>,<span class="st">"thistle"</span>)) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11"></a>  <span class="fu">theme</span>( <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(), <span class="at">legend.position =</span> <span class="st">"bottom"</span> )<span class="sc">+</span></span>
<span id="cb21-12"><a href="#cb21-12"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age Group"</span>, <span class="at">y=</span> <span class="st">"Heart Attack"</span>, <span class="at">fill=</span><span class="st">"Heart Attack"</span>)<span class="sc">+</span> </span>
<span id="cb21-13"><a href="#cb21-13"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent)</span>
<span id="cb21-14"><a href="#cb21-14"></a></span>
<span id="cb21-15"><a href="#cb21-15"></a>(p1<span class="sc">+</span>p2)<span class="sc">+</span> <span class="fu">plot_annotation</span>(<span class="at">title=</span> <span class="st">"Heart attack occurrence is not significantly associated with Gender and Age groups"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Insights
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Based on the stacked bar chart above, the chances of having heart attack is similar for both genders. This suggests that gender is not be a significant differentiator for heart attack occurrence in this study population.</p></li>
<li><p>Surprisingly, the proportion of Young adults having heart attack is comparable to that of Middle-aged and Old adults. This finding is in disaccordance with common assumptions of heart attack occurring predominantly in older adults, signifying that heart attack may become more common in young adults in the future. Understanding causes and risk factors for heart attack in young adults is therefore pertinent, for the development of effective prevention strategies and government-initiated public health interventions.</p></li>
</ul>
</div>
</div>
</section>
</section>
<section id="bmi-and-heart-attack-occurrrence" class="level3">
<h3 class="anchored" data-anchor-id="bmi-and-heart-attack-occurrrence"><strong>4.2 BMI and Heart Attack Occurrrence</strong></h3>
<p>Next, we examine BMI distribution by age and gender, before investigating association of BMI categories with heart attack occurrence.</p>
<p>The <code>ggplot()</code>, <code>geom_boxplot()</code> and <code>coord_flip()</code> functions in the <em>ggplot2</em> package are used to create the boxplot for BMI grouped by Age groups, colored by gender and change the orientation of the plot. The <code>stat_halfeye()</code> function from the <em>ggdist</em> package is used to show the BMI distributions for each Age group, by gender. The <code>theme()</code> and <code>lab()</code> functions in the <em>ggplot2</em> package are then used to change axis labels and dictate legend position.</p>
<p>The <code>ggbarstats()</code> and <code>grouped_ggbarstats()</code> functions from <em>ggstatsplot</em> package are used to create the stacked bar charts with Chi-square test statistics. <code>digits.perc</code>, <code>label.args</code>, <code>sample.size.label.args</code>, <code>label.args</code>,ggplot.component` were used to specify the label size, color and axis labels.</p>
<p>The <code>table()</code> function is used to create contingency table before applying the chisq.test()` function from base R to compute the Chi-square results to extract the Chi-square residuals data.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">Total Population</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Grouped by age</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false">Chi-squared Test</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>p1<span class="ot">&lt;-</span><span class="fu">ggplot</span>(df, </span>
<span id="cb22-2"><a href="#cb22-2"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Age_Groups, </span>
<span id="cb22-3"><a href="#cb22-3"></a>           <span class="at">y =</span> BMI,</span>
<span id="cb22-4"><a href="#cb22-4"></a>           <span class="at">fill=</span>Gender)) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5"></a>  <span class="fu">stat_halfeye</span>(<span class="at">adjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb22-6"><a href="#cb22-6"></a>               <span class="at">justification =</span> <span class="sc">-</span><span class="fl">0.1</span>,</span>
<span id="cb22-7"><a href="#cb22-7"></a>               <span class="at">.width =</span> <span class="dv">0</span>,</span>
<span id="cb22-8"><a href="#cb22-8"></a>               <span class="at">point_colour =</span> <span class="cn">NA</span>,</span>
<span id="cb22-9"><a href="#cb22-9"></a>                <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.1</span>)) <span class="sc">+</span></span>
<span id="cb22-10"><a href="#cb22-10"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> .<span class="dv">2</span>,</span>
<span id="cb22-11"><a href="#cb22-11"></a>               <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.3</span>),</span>
<span id="cb22-12"><a href="#cb22-12"></a>               <span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb22-13"><a href="#cb22-13"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb22-14"><a href="#cb22-14"></a>       <span class="at">y =</span> <span class="st">"BMI"</span>) <span class="sc">+</span>   </span>
<span id="cb22-15"><a href="#cb22-15"></a>  <span class="fu">theme</span>(</span>
<span id="cb22-16"><a href="#cb22-16"></a>    <span class="at">legend.position =</span> <span class="st">"right"</span>,</span>
<span id="cb22-17"><a href="#cb22-17"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span><span class="dv">1</span>, <span class="at">angle=</span><span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb22-18"><a href="#cb22-18"></a>  <span class="fu">coord_flip</span>()<span class="sc">+</span></span>
<span id="cb22-19"><a href="#cb22-19"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">alpha</span>(<span class="fu">c</span>(<span class="st">"thistle"</span>, <span class="st">"lightsteelblue"</span>),<span class="fl">0.35</span>))</span>
<span id="cb22-20"><a href="#cb22-20"></a></span>
<span id="cb22-21"><a href="#cb22-21"></a>p2<span class="ot">&lt;-</span><span class="fu">ggbarstats</span>(df, </span>
<span id="cb22-22"><a href="#cb22-22"></a>           <span class="at">y =</span> Heart_Attack_Occurrence, </span>
<span id="cb22-23"><a href="#cb22-23"></a>           <span class="at">x =</span> BMI_Category,</span>
<span id="cb22-24"><a href="#cb22-24"></a>           <span class="at">digits.perc =</span> <span class="dv">1</span>,</span>
<span id="cb22-25"><a href="#cb22-25"></a>           <span class="at">label.args =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">fill =</span> <span class="st">"white"</span>),</span>
<span id="cb22-26"><a href="#cb22-26"></a>  <span class="at">sample.size.label.args =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="fl">2.5</span>),</span>
<span id="cb22-27"><a href="#cb22-27"></a>  <span class="at">legend.title =</span> <span class="st">"BMI"</span>,</span>
<span id="cb22-28"><a href="#cb22-28"></a>  <span class="at">xlab=</span><span class="st">"Heart Attack"</span>,</span>
<span id="cb22-29"><a href="#cb22-29"></a>  <span class="at">ggplot.component =</span> <span class="fu">list</span>(<span class="fu">theme</span>( <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()), <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"rosybrown2"</span>,<span class="st">"thistle"</span>,<span class="st">"lightsteelblue"</span>,<span class="st">"lightcyan3"</span>))</span>
<span id="cb22-30"><a href="#cb22-30"></a>           ))</span>
<span id="cb22-31"><a href="#cb22-31"></a></span>
<span id="cb22-32"><a href="#cb22-32"></a>p1<span class="sc">/</span>p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a>p<span class="ot">&lt;-</span><span class="fu">grouped_ggbarstats</span>(df, </span>
<span id="cb23-2"><a href="#cb23-2"></a>           <span class="at">y =</span> Heart_Attack_Occurrence, </span>
<span id="cb23-3"><a href="#cb23-3"></a>           <span class="at">x =</span> BMI_Category,</span>
<span id="cb23-4"><a href="#cb23-4"></a>           <span class="at">digits.perc =</span> <span class="dv">1</span>, </span>
<span id="cb23-5"><a href="#cb23-5"></a>           <span class="at">grouping.var =</span> Age_Groups, </span>
<span id="cb23-6"><a href="#cb23-6"></a>           <span class="at">plotgrid.args =</span> <span class="fu">list</span>(<span class="at">ncol =</span> <span class="dv">2</span>),</span>
<span id="cb23-7"><a href="#cb23-7"></a>           <span class="at">sample.size.label.args =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="fl">2.5</span>),</span>
<span id="cb23-8"><a href="#cb23-8"></a>           <span class="at">label.args =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">fill =</span> <span class="st">"white"</span>), </span>
<span id="cb23-9"><a href="#cb23-9"></a>           <span class="at">ggplot.component =</span> <span class="fu">list</span>(<span class="fu">theme</span>(<span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>), <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()), <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"rosybrown2"</span>,<span class="st">"thistle"</span>,<span class="st">"lightsteelblue"</span>,<span class="st">"lightcyan3"</span>))),</span>
<span id="cb23-10"><a href="#cb23-10"></a>           <span class="at">legend.title =</span> <span class="st">"BMI"</span>,</span>
<span id="cb23-11"><a href="#cb23-11"></a>            <span class="at">xlab=</span><span class="st">"Heart Attack"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="images/clipboard-2307200117.png" class="img-fluid"></p>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<p>Chi-square test residual table for whole population</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="co">#Create contingency table</span></span>
<span id="cb24-2"><a href="#cb24-2"></a>contingency_table <span class="ot">&lt;-</span> <span class="fu">table</span>(df<span class="sc">$</span>BMI_Category, df<span class="sc">$</span>Heart_Attack_Occurrence)</span>
<span id="cb24-3"><a href="#cb24-3"></a></span>
<span id="cb24-4"><a href="#cb24-4"></a><span class="co"># Perform chi-square test</span></span>
<span id="cb24-5"><a href="#cb24-5"></a>chi_square_test <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(contingency_table)</span>
<span id="cb24-6"><a href="#cb24-6"></a></span>
<span id="cb24-7"><a href="#cb24-7"></a><span class="co"># View the results</span></span>
<span id="cb24-8"><a href="#cb24-8"></a>pearson_residuals <span class="ot">&lt;-</span> chi_square_test<span class="sc">$</span>residuals</span>
<span id="cb24-9"><a href="#cb24-9"></a><span class="fu">print</span>(pearson_residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             
                      No        Yes
  Underweight  0.4921282 -1.4863132
  Normal      -0.5867653  1.7721340
  Overweight  -0.1104517  0.3335834
  Obese        0.7163291 -2.1634392</code></pre>
</div>
</div>
<p>Chi-square test residual table for Young Adults</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="co">#Create contingency table</span></span>
<span id="cb26-2"><a href="#cb26-2"></a>subset_df<span class="ot">&lt;-</span>df[df<span class="sc">$</span>Age_Groups<span class="sc">==</span><span class="st">'Young'</span>,]</span>
<span id="cb26-3"><a href="#cb26-3"></a>contingency_table <span class="ot">&lt;-</span> <span class="fu">table</span>(subset_df<span class="sc">$</span>BMI_Category, subset_df<span class="sc">$</span>Heart_Attack_Occurrence)</span>
<span id="cb26-4"><a href="#cb26-4"></a></span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="co"># Perform chi-square test</span></span>
<span id="cb26-6"><a href="#cb26-6"></a>chi_square_test <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(contingency_table)</span>
<span id="cb26-7"><a href="#cb26-7"></a></span>
<span id="cb26-8"><a href="#cb26-8"></a><span class="co"># View the results</span></span>
<span id="cb26-9"><a href="#cb26-9"></a>pearson_residuals <span class="ot">&lt;-</span> chi_square_test<span class="sc">$</span>residuals</span>
<span id="cb26-10"><a href="#cb26-10"></a><span class="fu">print</span>(pearson_residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             
                      No        Yes
  Underweight  0.2641421 -0.8146029
  Normal      -0.4873117  1.5028483
  Overweight  -0.1114740  0.3437812
  Obese        0.7150849 -2.2052912</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Insights
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Distribution of BMI is consistent across age group and gender, resembing a normal distribution. This indicates that BMI is not associated with gender or age in the population.</p></li>
<li><p>BMI category is associated with heart attack occurrence (Chi-square p-value&lt;0.05). Interestingly, there were significantly less obese individuals experiencing heart attack than expected, based on the large negative Chi-square residual value (-2.16). However, when stratified by age groups, this association remained significant for young adults only. This suggests that the association may be age-specific and that the effect of BMI on heart attack occurrence might be more pronounced in younger individuals, who may not have developed other comorbidities yet (e.g., hypertension, high cholesterol).</p></li>
</ul>
</div>
</div>
<section id="association-of-heart-attack-with-hypertension-and-cholesterol" class="level4">
<h4 class="anchored" data-anchor-id="association-of-heart-attack-with-hypertension-and-cholesterol"><strong>4.3 Association of Heart Attack with Hypertension and Cholesterol</strong></h4>
<p>Given the high incidence of hypertension observed in the earlier section, we will investigate whether hypertension is associated with an increased risk of heart attack.</p>
<p>Mosaic plots were created using <code>geom_mosaic()</code> from the <em>ggmosaic</em> package and <code>ggplot()</code> from the <em>ggplot2</em> package. <code>labs()</code>, <code>theme()</code> and <code>scale_fill_manual</code> from <em>ggplot2</em> package were used to change the axis labels, theme and color of the graphs. <code>facet_wrap()</code> was used to facet the mosaic plots by Age Group. <code>scale_y_continuous()</code> from <em>ggplot2</em> was used to display the percentages.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a>p1<span class="ot">&lt;-</span><span class="fu">ggplot</span>(<span class="at">data=</span>df) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2"></a>  <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(Blood_Pressure,Heart_Attack_Occurrence), <span class="at">fill=</span>Blood_Pressure))<span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"right"</span>) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Blood Pressure"</span>,</span>
<span id="cb28-5"><a href="#cb28-5"></a>       <span class="at">x =</span> <span class="st">"Heart Attack"</span>)<span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6"></a><span class="fu">scale_fill_manual</span>(<span class="st">"Heart Attack"</span>,<span class="at">values=</span><span class="fu">c</span>( <span class="st">"lightsteelblue"</span>,<span class="st">"lightcyan3"</span>, <span class="st">"thistle"</span>,<span class="st">"rosybrown2"</span>))<span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent)<span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Age_Groups)</span>
<span id="cb28-9"><a href="#cb28-9"></a></span>
<span id="cb28-10"><a href="#cb28-10"></a>p2<span class="ot">&lt;-</span><span class="fu">ggplot</span>(<span class="at">data=</span>df) <span class="sc">+</span></span>
<span id="cb28-11"><a href="#cb28-11"></a>  <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(Cholesterol_Category,Heart_Attack_Occurrence), <span class="at">fill=</span>Cholesterol_Category))<span class="sc">+</span></span>
<span id="cb28-12"><a href="#cb28-12"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"right"</span>) <span class="sc">+</span></span>
<span id="cb28-13"><a href="#cb28-13"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Cholesterol Level"</span>,</span>
<span id="cb28-14"><a href="#cb28-14"></a>       <span class="at">x =</span> <span class="st">"Heart Attack Occurrence"</span>)<span class="sc">+</span></span>
<span id="cb28-15"><a href="#cb28-15"></a><span class="fu">scale_fill_manual</span>(<span class="st">"Heart Attack"</span>,<span class="at">values=</span><span class="fu">c</span>( <span class="st">"lightsteelblue"</span>,<span class="st">"lightcyan3"</span>, <span class="st">"thistle"</span>))<span class="sc">+</span></span>
<span id="cb28-16"><a href="#cb28-16"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Age_Groups) <span class="sc">+</span> </span>
<span id="cb28-17"><a href="#cb28-17"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent)</span>
<span id="cb28-18"><a href="#cb28-18"></a></span>
<span id="cb28-19"><a href="#cb28-19"></a>p1<span class="sc">/</span>p2 <span class="sc">+</span> <span class="fu">plot_layout</span>(<span class="at">axis_titles =</span> <span class="st">"collect"</span>)<span class="sc">+</span> <span class="fu">plot_annotation</span>(<span class="at">title=</span> <span class="st">"Heart Attack is not significantly associated with Hypertension and Cholesterol Level"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Insights
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Heart attack occurrence does not significantly increase in groups with hypertension or elevated blood pressure, compared to normal blood pressure, across all age groups.</p></li>
<li><p>Similarly, individuals with elevated cholesterol levels do not have increased risk of heart attack occurrence regardless of age groups.</p></li>
<li><p>The findings suggests that high blood pressure or cholesterol levels alone may only have a small impact on heart attack risk or that medication adherence and lifestyle modifications could play a role in mitigating the associated risks. The overall heart attack risk for an individual may only become more pronounced when multiple factors are accounted for, as presence of multiple risk factors simultaneously compounds the overall risks since each condition can exacerbate the others.</p></li>
</ul>
</div>
</div>
</section>
<section id="association-of-heart-attack-with-medical-history" class="level4">
<h4 class="anchored" data-anchor-id="association-of-heart-attack-with-medical-history"><strong>4.4 Association of Heart Attack with Medical History</strong></h4>
<p>Heart attack is typically caused by a combination of various interrelated risk factors. Therefore, it is essential to examine other factors such as underlying medical conditions, family history, and lifestyle choices. These factors may interact in complex ways, increasing the likelihood of heart attacks.</p>
<p>In this section, we will investigate if Diabetes History and Family History increases tendency of heart attack occurrence.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">Family history &amp; Diabetes Mosaic Plot</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Diabetes by Age Group</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-3" role="tab" aria-controls="tabset-4-3" aria-selected="false">Chi-square test</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a>p1<span class="ot">&lt;-</span><span class="fu">ggplot</span>(<span class="at">data=</span>df) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2"></a>  <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(Heart_Attack_Occurrence,Diabetes_History), <span class="at">fill=</span>Heart_Attack_Occurrence))<span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"right"</span>) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Diabetes History"</span>,</span>
<span id="cb29-5"><a href="#cb29-5"></a>       <span class="at">y =</span> <span class="st">"Heart Attack Occurrence"</span>)<span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6"></a><span class="fu">scale_fill_manual</span>(<span class="st">"Heart Attack"</span>,<span class="at">values=</span><span class="fu">c</span>( <span class="st">"lightsteelblue"</span>, <span class="st">"thistle"</span>))<span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent)</span>
<span id="cb29-8"><a href="#cb29-8"></a></span>
<span id="cb29-9"><a href="#cb29-9"></a>p2<span class="ot">&lt;-</span><span class="fu">ggplot</span>(<span class="at">data=</span>df) <span class="sc">+</span></span>
<span id="cb29-10"><a href="#cb29-10"></a>  <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(Heart_Attack_Occurrence,Family_History), <span class="at">fill=</span>Heart_Attack_Occurrence))<span class="sc">+</span></span>
<span id="cb29-11"><a href="#cb29-11"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"right"</span>) <span class="sc">+</span></span>
<span id="cb29-12"><a href="#cb29-12"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Family History"</span>,</span>
<span id="cb29-13"><a href="#cb29-13"></a>       <span class="at">y =</span> <span class="st">"Heart Attack Occurrence"</span>)<span class="sc">+</span></span>
<span id="cb29-14"><a href="#cb29-14"></a><span class="fu">scale_fill_manual</span>(<span class="st">"Heart Attack"</span>,<span class="at">values=</span><span class="fu">c</span>( <span class="st">"lightsteelblue"</span>, <span class="st">"thistle"</span>))<span class="sc">+</span></span>
<span id="cb29-15"><a href="#cb29-15"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Age_Groups) <span class="sc">+</span> </span>
<span id="cb29-16"><a href="#cb29-16"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent)</span>
<span id="cb29-17"><a href="#cb29-17"></a>p2<span class="sc">/</span>p1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="fu">grouped_ggbarstats</span>(df, </span>
<span id="cb30-2"><a href="#cb30-2"></a>           <span class="at">y =</span> Heart_Attack_Occurrence, </span>
<span id="cb30-3"><a href="#cb30-3"></a>           <span class="at">x =</span> Diabetes_History,</span>
<span id="cb30-4"><a href="#cb30-4"></a>           <span class="at">digits.perc =</span> <span class="dv">1</span>, </span>
<span id="cb30-5"><a href="#cb30-5"></a>           <span class="at">grouping.var =</span> Age_Groups, </span>
<span id="cb30-6"><a href="#cb30-6"></a>           <span class="at">plotgrid.args =</span> <span class="fu">list</span>(<span class="at">ncol =</span> <span class="dv">2</span>),</span>
<span id="cb30-7"><a href="#cb30-7"></a>           <span class="at">sample.size.label.args =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="fl">2.5</span>),</span>
<span id="cb30-8"><a href="#cb30-8"></a>           <span class="at">label.args =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">fill =</span> <span class="st">"white"</span>), </span>
<span id="cb30-9"><a href="#cb30-9"></a>           <span class="at">legend.title =</span> <span class="st">"Diabetes History"</span>,</span>
<span id="cb30-10"><a href="#cb30-10"></a>           <span class="at">xlab=</span><span class="st">"Heart Attack"</span>,</span>
<span id="cb30-11"><a href="#cb30-11"></a>           <span class="at">ggplot.component =</span> <span class="fu">list</span>(<span class="fu">theme</span>(<span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>), <span class="at">axis.ticks.x=</span><span class="fu">element_blank</span>()),<span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"thistle"</span>,<span class="st">"lightsteelblue"</span>))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><img src="images/clipboard-4138769921.png" class="img-fluid"></p>
</div>
<div id="tabset-4-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-3-tab">
<p>Chi-square test residual table for Young Adults</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="co">#Create contingency table</span></span>
<span id="cb31-2"><a href="#cb31-2"></a>subset_df<span class="ot">&lt;-</span>df[df<span class="sc">$</span>Age_Groups<span class="sc">==</span><span class="st">'Young'</span>,]</span>
<span id="cb31-3"><a href="#cb31-3"></a>contingency_table <span class="ot">&lt;-</span> <span class="fu">table</span>(subset_df<span class="sc">$</span>Diabetes_History, subset_df<span class="sc">$</span>Heart_Attack_Occurrence)</span>
<span id="cb31-4"><a href="#cb31-4"></a></span>
<span id="cb31-5"><a href="#cb31-5"></a><span class="co"># Perform chi-square test</span></span>
<span id="cb31-6"><a href="#cb31-6"></a>chi_square_test <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(contingency_table)</span>
<span id="cb31-7"><a href="#cb31-7"></a></span>
<span id="cb31-8"><a href="#cb31-8"></a><span class="co"># View the results</span></span>
<span id="cb31-9"><a href="#cb31-9"></a>pearson_residuals <span class="ot">&lt;-</span> chi_square_test<span class="sc">$</span>residuals</span>
<span id="cb31-10"><a href="#cb31-10"></a><span class="fu">print</span>(pearson_residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
              No        Yes
  No   0.3881721 -1.1971061
  Yes -0.7609653  2.3467842</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Insights
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Proportion of individuals with heart attack did not differ significantly between groups with or without family history, across the age groups.</p></li>
<li><p>Interestingly, proportion of individuals who have experienced heart attack was similar for individuals with or without diabetes history for the overall population but heart attack occurrence is associated with diabetes history in Young Adults (Chi-square p-value&lt;0.05) when the data is age-stratified. There is increased tendency of young adults with diabetes history experiencing heart attack compared to young adults without diabetes history, based on the large positive Chi-square residual value of 2.34.</p></li>
</ul>
</div>
</div>
</section>
<section id="lifestyle-factors-and-heart-attack-occurrence" class="level4">
<h4 class="anchored" data-anchor-id="lifestyle-factors-and-heart-attack-occurrence"><strong>4.5 Lifestyle Factors and Heart Attack Occurrence</strong></h4>
<p>In this section, we will investigate if lifestyle factors like physical activity, diet quality and alcohol consumption are associated with heart attack.</p>
<p>The <code>gglikert()</code> function from <em>ggstats</em> package is used to create the diverging bar charts. <code>scale_fill_brewer()</code>, <code>theme()</code> and <code>labs()</code> from *ggplot2` package is used to set the color palette, change axis labels and ticks.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="co"># Create the subset data for "Yes" and "No" heart attack occurrences</span></span>
<span id="cb33-2"><a href="#cb33-2"></a>HA_y <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Heart_Attack_Occurrence <span class="sc">==</span> <span class="st">"Yes"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Physical_Activity, Diet_Quality, Alcohol_Consumption)</span>
<span id="cb33-3"><a href="#cb33-3"></a>HA_n <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Heart_Attack_Occurrence <span class="sc">==</span> <span class="st">"No"</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Physical_Activity, Diet_Quality, Alcohol_Consumption)</span>
<span id="cb33-4"><a href="#cb33-4"></a></span>
<span id="cb33-5"><a href="#cb33-5"></a><span class="co"># Find the maximum length of the two subsets</span></span>
<span id="cb33-6"><a href="#cb33-6"></a>max_len <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">nrow</span>(HA_y), <span class="fu">nrow</span>(HA_n))</span>
<span id="cb33-7"><a href="#cb33-7"></a></span>
<span id="cb33-8"><a href="#cb33-8"></a><span class="co"># Pad the shorter dataframe with NAs</span></span>
<span id="cb33-9"><a href="#cb33-9"></a>HA_y <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(HA_y, <span class="fu">data.frame</span>(<span class="at">Physical_Activity =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, max_len <span class="sc">-</span> <span class="fu">nrow</span>(HA_y)), <span class="at">Diet_Quality =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, max_len <span class="sc">-</span> <span class="fu">nrow</span>(HA_y)),<span class="at">Alcohol_Consumption =</span> <span class="fu">rep</span>(<span class="cn">NA</span>, max_len <span class="sc">-</span> <span class="fu">nrow</span>(HA_y))))</span>
<span id="cb33-10"><a href="#cb33-10"></a></span>
<span id="cb33-11"><a href="#cb33-11"></a>PA<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">Yes=</span>HA_y<span class="sc">$</span>Physical_Activity, <span class="at">No=</span>HA_n<span class="sc">$</span>Physical_Activity)</span>
<span id="cb33-12"><a href="#cb33-12"></a></span>
<span id="cb33-13"><a href="#cb33-13"></a>DQ<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">Yes=</span>HA_y<span class="sc">$</span>Diet_Quality, <span class="at">No=</span>HA_n<span class="sc">$</span>Diet_Quality)</span>
<span id="cb33-14"><a href="#cb33-14"></a></span>
<span id="cb33-15"><a href="#cb33-15"></a>AC<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">Yes=</span>HA_y<span class="sc">$</span>Alcohol_Consumption, <span class="at">No=</span>HA_n<span class="sc">$</span>Alcohol_Consumption)</span>
<span id="cb33-16"><a href="#cb33-16"></a></span>
<span id="cb33-17"><a href="#cb33-17"></a>p1<span class="ot">&lt;-</span><span class="fu">gglikert</span>(PA) <span class="sc">+</span> </span>
<span id="cb33-18"><a href="#cb33-18"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette=</span><span class="st">"Blues"</span>) <span class="sc">+</span></span>
<span id="cb33-19"><a href="#cb33-19"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Physical Activity"</span>, <span class="at">y=</span><span class="st">"Heart Attack"</span>)<span class="sc">+</span></span>
<span id="cb33-20"><a href="#cb33-20"></a>  <span class="fu">theme</span>(<span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb33-21"><a href="#cb33-21"></a>        <span class="at">axis.ticks.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb33-22"><a href="#cb33-22"></a>        <span class="at">axis.text.x=</span><span class="fu">element_blank</span>())</span>
<span id="cb33-23"><a href="#cb33-23"></a></span>
<span id="cb33-24"><a href="#cb33-24"></a>p2<span class="ot">&lt;-</span><span class="fu">gglikert</span>(DQ) <span class="sc">+</span> </span>
<span id="cb33-25"><a href="#cb33-25"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette=</span><span class="st">"Set1"</span>) <span class="sc">+</span></span>
<span id="cb33-26"><a href="#cb33-26"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Diet Quality"</span>, <span class="at">y=</span><span class="st">"Heart Attack"</span>)<span class="sc">+</span></span>
<span id="cb33-27"><a href="#cb33-27"></a>  <span class="fu">theme</span>(<span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb33-28"><a href="#cb33-28"></a>        <span class="at">axis.ticks.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb33-29"><a href="#cb33-29"></a>        <span class="at">axis.text.x=</span><span class="fu">element_blank</span>())</span>
<span id="cb33-30"><a href="#cb33-30"></a></span>
<span id="cb33-31"><a href="#cb33-31"></a></span>
<span id="cb33-32"><a href="#cb33-32"></a>p3<span class="ot">&lt;-</span><span class="fu">gglikert</span>(AC) <span class="sc">+</span> </span>
<span id="cb33-33"><a href="#cb33-33"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette=</span><span class="st">"Blues"</span>) <span class="sc">+</span></span>
<span id="cb33-34"><a href="#cb33-34"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Alcohol Consumption"</span>, <span class="at">y=</span><span class="st">"Heart Attack"</span>)<span class="sc">+</span></span>
<span id="cb33-35"><a href="#cb33-35"></a>  <span class="fu">theme</span>(<span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb33-36"><a href="#cb33-36"></a>        <span class="at">axis.ticks.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb33-37"><a href="#cb33-37"></a>        <span class="at">axis.text.x=</span><span class="fu">element_blank</span>())</span>
<span id="cb33-38"><a href="#cb33-38"></a></span>
<span id="cb33-39"><a href="#cb33-39"></a>(p1<span class="sc">+</span>p2)<span class="sc">/</span>p3<span class="sc">+</span> <span class="fu">plot_annotation</span>(<span class="at">title=</span><span class="st">"Heart attack is not associated with Physical Activity, Diet Quality</span><span class="sc">\n</span><span class="st">&amp;Alcohol consumption"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex01_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Insights
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Heart attack occurrence does not vary significantly with Physical Activity, Diet Quality and Alcohol Consumption. This suggests that lifestyle factors may a secondary or insignificant role in heart attack risk for the study population. However, the data for these variables are measured on a likert scale which may be prone to biases, leading to potential inaccuracies and weaken the observed relationship between lifestyle factors and heart attack occurrence.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion"><strong>5 Conclusion</strong></h3>
<p>Our analyses reveals a high prevalence of heart attack occurrence in the Japanese population, with approximately 10% affected, raising a cause for concern and emphasizes a pressing need for targeted cardiovascular health initiatives. Furthermore, significant portions of the population suffers from hypertension, elevated cholesterol levels, and/or are overweight or obese, all of which are well-known risk factors for heart disease.</p>
<p>More importantly, heart attack incidence is comparable between young adults (18-39) and adults aged 40 and above, highlighting an emerging concern for cardiovascular health in younger populations. In our analyses, BMI category was found to be associated with heart attack occurrence, particularly in young adults, suggesting age-specific effects. Diabetes history was additionally associated with heart attack in young adults.</p>
<p>On the other hand, hypertension, elevated cholesterol levels, family history, physical activity, diet quality, and alcohol consumption did not show a significant relationship with heart attack occurrence in this population.</p>
<p>These findings underscore the need for more comprehensive studies to identify heart attack risk factors among younger adults. Future research and analyses could focus on exploring the complex interactions between risk factors to provide a clearer understanding of the risk profiles for heart attack in different demographic groups.</p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references"><strong>6 References</strong></h3>
<ul>
<li><a href="https://www.sciencedaily.com/releases/2019/03/190307081026.htm">Heart Attack Research</a></li>
<li><a href="https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings">Blood Pressure Categories</a></li>
<li><a href="https://www.cdc.gov/bmi/adult-calculator/bmi-categories.html">BMI Categories</a></li>
<li><a href="https://www.myheart.org.sg/heart-news/cholesterol-levels/">Cholesterol Level Categories</a></li>
<li><a href="https://www.datacamp.com/tutorial/chi-square-test-r">Chi-square test</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/www\.jiarong-visual-analytics\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>