project:
  type: website

website:
  page-navigation: true
  reader-mode: true
  title: "ISSS608"
  site-url: https://www.jiarong-visual-analytics.netlify.app
  open-graph: true
  navbar:
    background: primary
    foreground: light
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 1"
        href: Hands_on_Exercise/Hands-on_Ex01.html
      - text: "Hands-on Exercise 2"
        href: Hands_on_Exercise/Hands-on_Ex02.html
      - text: "Hands-on Exercise 3a"
        href: Hands_on_Exercise/Hands-on_Ex03a.html
      - text: "Hands-on Exercise 3b"
        href: Hands_on_Exercise/Hands-on_Ex03b.html
      - text: "Hands-on Exercise 4a"
        href: Hands_on_Exercise/Hands-on_Ex04a.html
      - text: "Hands-on Exercise 4b"
        href: Hands_on_Exercise/Hands-on_Ex04b.html
      - text: "Hands-on Exercise 4c"
        href: Hands_on_Exercise/Hands-on_Ex04c.html
      - text: "Hands-on Exercise 4d"
        href: Hands_on_Exercise/Hands-on_Ex04d.html
      - text: "Hands-on Exercise 5a"
        href: Hands_on_Exercise/Hands-on_Ex05a.html
      - text: "Hands-on Exercise 5b"
        href: Hands_on_Exercise/Hands-on_Ex05b.html
      - text: "Hands-on Exercise 5c"
        href: Hands_on_Exercise/Hands-on_Ex05c.html
      - text: "Hands-on Exercise 5d"
        href: Hands_on_Exercise/Hands-on_Ex05d.html
      - text: "Hands-on Exercise 5e"
        href: Hands_on_Exercise/Hands-on_Ex05e.html
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 4"
        href: In-class_Ex04.html
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take-home_Exercise/Take-home_Ex01/Take-home_Ex01.html
    right:
      - icon: house-fill
        href: index.qmd
        text: 'Home'
      - icon: person-workspace
        href: about.qmd
        text: 'About'
  sidebar:
    - title: 'Hands-on Exercises'
      style: "docked"
      search: true
      contents:
        - section: "Hands-on Exercises"
          contents:
            - href: Hands_on_Exercise/Hands-on_Ex01.html
              text: "Hands-on Exercise 1"
            - text: "Hands-on Exercise 2"
              href: Hands_on_Exercise/Hands-on_Ex02.html
            - text: "Hands-on Exercise 3a"
              href: Hands_on_Exercise/Hands-on_Ex03a.html
            - text: "Hands-on Exercise 3b"
              href: Hands_on_Exercise/Hands-on_Ex03b.html
            - text: "Hands-on Exercise 4a"
              href: Hands_on_Exercise/Hands-on_Ex04a.html
            - text: "Hands-on Exercise 4b"
              href: Hands_on_Exercise/Hands-on_Ex04b.html
            - text: "Hands-on Exercise 4c"
              href: Hands_on_Exercise/Hands-on_Ex04c.html
            - text: "Hands-on Exercise 4d"
              href: Hands_on_Exercise/Hands-on_Ex04d.html
            - text: "Hands-on Exercise 5a"
              href: Hands_on_Exercise/Hands-on_Ex05a.html
            - text: "Hands-on Exercise 5b"
              href: Hands_on_Exercise/Hands-on_Ex05b.html
            - text: "Hands-on Exercise 5c"
              href: Hands_on_Exercise/Hands-on_Ex05c.html
            - text: "Hands-on Exercise 5d"
              href: Hands_on_Exercise/Hands-on_Ex05d.html
            - text: "Hands-on Exercise 5e"
              href: Hands_on_Exercise/Hands-on_Ex05e.html
              
    - title: 'placeholder'
      

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
    toc-depth: 6
    toc-title: "Table of Contents"
    mainfont: 'cursive'
    fontsize: 0.9em

editor: visual

