project:
  type: website

website:
  page-navigation: true
  reader-mode: true
  title: "ISSS608"
  site-url: https://www.jiarong-visual-analytics.netlify.app
  open-graph: true
  navbar:
    background: primary
    foreground: light
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 0"
        href: Hands_on_Exercise/Hands-on_Ex00.html
      - text: "Hands-on Exercise 1"
        href: Hands_on_Exercise/Hands-on_Ex01.html
      - text: "Hands-on Exercise 2"
        href: Hands_on_Exercise/Hands-on_Ex02.html
      - text: "Hands-on Exercise 3"
        href: Hands_on_Exercise/Hands-on_Ex03.html
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: In-class_Ex1.html
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take-home_Ex1.html"
    right:
      - icon: house-fill
        href: index.qmd
        text: 'Home'
      - icon: person-workspace
        href: about.qmd
        text: 'About'
  sidebar:
    - title: 'Hands-on Exercises'
      style: "docked"
      search: true
      contents:
        - section: "Hands-on Exercises"
          contents:
            - href: Hands_on_Exercise/Hands-on_Ex00.html
              text: "Hands-on Exercise 0"
            - href: Hands_on_Exercise/Hands-on_Ex01.html
              text: "Hands-on Exercise 1"
            - text: "Hands-on Exercise 2"
              href: Hands_on_Exercise/Hands-on_Ex02.html
            - text: "Hands-on Exercise 3"
              href: Hands_on_Exercise/Hands-on_Ex03.html
    - title: 'placeholder'
      

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
    toc-depth: 6
    toc-title: "Table of Contents"
    mainfont: 'cursive'
    fontsize: 0.9em

editor: visual

