project:
  type: website

website:
  reader-mode: true
  title: "ISSS608"
  navbar:
    background: primary
    foreground: light
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 0"
        href: Hands_on_Exercise/Hands-on_Ex00.html
      - text: "Hands-on Exercise 1"
        href: Hands_on_Exercise/Hands-on_Ex01.html
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: In-class_Ex1.html
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: Take-home_Ex1.html"
    right:
      - icon: house-fill
        href: index.qmd
        text: 'Home'
      - icon: person-workspace
        href: about.qmd
        text: 'About'

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
    toc-depth: 6
    mainfont: 'cursive'
    fontsize: 1.0em

editor: visual

